### ISSUE TITLE
Question about a specific part of the code

### ISSUE THREAD

**Issue by raulsenaferreira** [ToshiHayashi/OCITN#3]
Hello, I'm reorganizing the code to better understand the method. 
However, there is a line of the code that I did not understand:

`for n in range(len(x_train)):`
 ` y_train[n]=y2.rotate(rot)`

It seems to me that you are putting the rotated image of Leena.png, n times (which n is the number of images in x_train) inside of a vector that should represent the labels of the training data. 
In your code the y_train is also a matrix because you do hotencoder, ok, However...
If it is the case, it seems wrong because it is just adding n times the image of leena.png inside of the train labels, putting RGB values instead of labels.

Maybe you wanted to put this image inside of an X to posteriorly feed the autoencoder, isn't it? 
and after it, correctly calculate the construction error regarding this image.

Thanks for sharing the code

**Comment by raulsenaferreira** [comment]
I saw now that you updated a code more accurate, so I will close this issue. Thanks

**Comment by ToshiHayashi** [comment]
Hello. Thank you for the issue. 

Yes, these codes are more accurate.
I will remove the old codes to avoid confusion.

If you have other questions, please feel free to let me know.
Thank you very much!
